### ISSUE TITLE
Why using Csma channels between edge switches and bridges?

### ISSUE THREAD

**Issue by jcarreira** [ntu-dsi-dcn/ntu-dsi-dcn#2]
I'm taking a look at the Fat-tree.cc benchmark and some things are not entirely clear. Can you please clarify?
1. Why do you create a Bridge between the edge switches and the hosts? Why not connect them with a PointToPoint channel?
2. Why use Csma channels for the links between bridges and edge switches, and edge switches and hosts? Aren't these half-duplex?

**Comment by ntu-dsi-dcn** [comment]
Hello,

My apologies for replying this late. Hope the following still helps.

1) Yes, you are right. You can connect them with a PointToPoint channel. There are various ways to implement the Fat-tree architecture. Our implementation is by no means the only way to realize the Fat-tree architecture. You are welcome to clone this project and modify accordingly, connecting the edge switches and the hosts with PointToPoint channels.

2) When we were developing these simulations at that time, we followed the ns-3 tutorials to try to realize the Fat-tree network architecture. In those tutorials, the Csma channels are used to link up the switches. We just stick to that. Performance considerations are not our primary concerns at that time. More importantly, we wanted to demonstrate the reproducibility of the underlying network architectures. Having said that, if you wish to, do feel free to suggest or contribute better ways to improve the Fat-tree network architecture implementation.

Anyway, you can reach us through email for better communication.
