### ISSUE TITLE
Framework compilation fails with g++ warnings/errors

### ISSUE THREAD

**Issue by nishprab** [ntu-dsi-dcn/ntu-dsi-dcn#3]
./waf fails with g++ warnings/errors consistently. This is on a Ubuntu 16.06 VM. All ns3 dependencies have been installed. Does the version of ns3 used need to be bumped up?

--snip--

[ 597/1285] cxx: src/wimax/model/burst-profile-manager.cc -> build/src/wimax/model/burst-profile-manager.cc.1.o
[ 598/1285] cxx: src/wimax/model/bs-scheduler-rtps.cc -> build/src/wimax/model/bs-scheduler-rtps.cc.1.o
In file included from ../src/wimax/model/wimax-connection.h:29:0,
                 from ../src/wimax/model/service-flow.h:27,
                 from ../src/wimax/model/bs-scheduler.h:31,
                 from ../src/wimax/model/bs-scheduler-rtps.h:32,
                 from ../src/wimax/model/bs-scheduler-rtps.cc:22:
../src/wimax/model/wimax-mac-queue.h: In member function ‘void ns3::BSSchedulerRtps::BSSchedulerRTPSConnection(uint32_t&)’:
../src/wimax/model/wimax-mac-queue.h:121:10: error: ‘struct ns3::WimaxMacQueue::QueueElement’ is private
   struct QueueElement
          ^
../src/wimax/model/bs-scheduler-rtps.cc:497:29: error: within this context
   std::deque<WimaxMacQueue::QueueElement>::const_iterator iter3;
                             ^
Waf: Leaving directory `/home/nishanth/ntu-dsi-dcn/build'
Build failed
 -> task failed (exit status 1): 
    {task 139653509164176: cxx bs-scheduler-rtps.cc -> bs-scheduler-rtps.cc.1.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-pthread', '-Ibuild', '-I.', '-I/usr/include/gtk-2.0', '-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include', '-I/usr/include/gio-unix-2.0', '-I/usr/include/cairo', '-I/usr/include/pango-1.0', '-I/usr/include/atk-1.0', '-I/usr/include/pixman-1', '-I/usr/include/libpng12', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/freetype2', '-I/usr/include/libxml2', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DSQLITE3=1', '-DHAVE_IF_TUN_H=1', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYTHON_H=1', '-DENABLE_GSL', '../src/wimax/model/bs-scheduler-rtps.cc', '-c', '-o', 'src/wimax/model/bs-scheduler-rtps.cc.1.o']

--snip--

**Comment by ntu-dsi-dcn** [comment]
Hi NishanthPrabhu, you might wish to try installing NTU-DSI-DCN on ns-3.13 and Ubuntu 12.04 LTS first before doing the migration to the latest ns-3 and Ubuntu LTS version.

We have added a mini guide in the README file to show how you can do the migration. Refer to https://github.com/ntu-dsi-dcn/ntu-dsi-dcn for more information.
