### ISSUE TITLE
ECMP in fat-tree

### ISSUE THREAD

**Issue by wangshuaizs** [ntu-dsi-dcn/ntu-dsi-dcn#4]
Hi，
   I ran fat-tree with k = 4 in my machine, and I found that only one core switch, one agg switch in each pod were used. I wonder why you did not taken ECMP into account? If ECMP is used, every switch can be used to improve throughput.

Thank you in advance!

**Comment by ntu-dsi-dcn** [comment]
Hello, 

Sorry for the late reply. 

At that time, performance considerations are not our primary focus. We are more focussed on giving people the ability to reproduce the fundamental network architectures for deeper research purposes. We simply stick to the default ns-3 Nix Vector Routing as the main routing strategy. We regret that we did not attempt to consider ECMP at that time.

You are right there. ECMP, as well as other routing strategies can be used to boost the throughput of Fat-tree and BCube network architectures.
